version: '3.8'

services:
  pdns-recursor-mysql:
    image: pschiffe/pdns-recursor:${RECURSOR_TAG:-latest}
    hostname: ns.globe.local
    container_name: pdns-recursor-mysql
    networks:
      pdns-net:
        ipv4_address: 172.22.0.53
    restart: unless-stopped
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - /srv/ddi/pdns/recursor.conf:/etc/pdns/recursor.conf:ro
      - /etc/localtime:/etc/localtime:ro
    ulimits:
      nofile:
        soft: 5000
        hard: 5000
    extra_hosts:
      - "pdns-mysql-master:172.22.0.30"
      - "pdns-mysql-slave:172.22.0.31"
    depends_on:
      - pdns-mysql-master
      - pdns-mysql-slave

  pdns-mariadb-master:
    image: mariadb:latest
    container_name: pdns-mariadb-master
    hostname: pdns-mariadb-master
    networks:
      pdns-net:
        ipv4_address: 172.22.0.20
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/ddi/pdns/master-db:/var/lib/mysql:Z
    ports:
      - "5319:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "master-secret-pw"
      MYSQL_DATABASE: "powerdnsmaster"
      MYSQL_USER: "powerdns"
      MYSQL_PASSWORD: "master-secret-pw"

  pdns-mariadb-slave:
    image: mariadb:latest
    container_name: pdns-mariadb-slave
    hostname: pdns-mariadb-slave
    networks:
      pdns-net:
        ipv4_address: 172.22.0.21
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/ddi/pdns/slave-db:/var/lib/mysql:Z
    ports:
      - "5320:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "slave-secret-pw"
      MYSQL_DATABASE: "powerdnsslave"
      MYSQL_USER: "powerdns"
      MYSQL_PASSWORD: "slave-secret-pw"

  pdns-mysql-master:
    image: pschiffe/pdns-mysql:${PDNS_MYSQL_TAG:-latest}
    hostname: ns1.globe.local
    container_name: pdns-mysql-master
    networks:
      pdns-net:
        ipv4_address: 172.22.0.30
        aliases:
          - pdns
    restart: unless-stopped
    ports:
      - "5300:53"
      - "5300:53/udp"
      - "8081:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/ddi/pdns/master:/etc/pdns/zones:ro
      - /srv/ddi/pdns/shared:/var/named:rw
    environment:
      PDNS_gmysql_host: "pdns-mariadb-master"
      PDNS_gmysql_dbname: "powerdnsmaster"
      PDNS_gmysql_user: "powerdns"
      PDNS_gmysql_password: "master-secret-pw"
      PDNS_master: "yes"
      PDNS_api: "yes"
      PDNS_api_key: "secret"
      PDNS_webserver: "yes"
      PDNS_webserver_address: "0.0.0.0"
      PDNS_webserver_allow_from: "172.16.0.0/12"
      PDNS_version_string: "anonymous"
      PDNS_default_ttl: "1500"
      PDNS_allow_axfr_ips: "172.22.0.31"
      PDNS_only_notify: "172.22.0.31"
      PDNS_gmysql-dnssec: "yes"
    depends_on:
      - pdns-mariadb-master

  pdns-mysql-slave:
    image: pschiffe/pdns-mysql:${PDNS_MYSQL_TAG:-latest}
    hostname: ns2.globe.local
    container_name: pdns-mysql-slave
    networks:
      pdns-net:
        ipv4_address: 172.22.0.31
    restart: unless-stopped
    ports:
      - "5301:53"
      - "5301:53/udp"
      - "8082:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      PDNS_gmysql_host: "pdns-mariadb-slave"
      PDNS_gmysql_dbname: "powerdnsslave"
      PDNS_gmysql_user: "powerdns"
      PDNS_gmysql_password: "slave-secret-pw"
      PDNS_slave: "yes"
      PDNS_superslave: "yes"
      PDNS_webserver: "yes"
      PDNS_webserver_address: "0.0.0.0"
      PDNS_webserver_allow_from: "172.16.0.0/12"
      PDNS_version_string: "anonymous"
      PDNS_disable_axfr: "no"
      PDNS_allow_notify_from: "172.22.0.30"
    depends_on:
      - pdns-mariadb-slave
      - pdns-mysql-master

  pdns-admin-mysql:
    image: pschiffe/pdns-admin
    hostname: pdns-admin-mysql
    container_name: pdns-admin-mysql
    networks:
      pdns-net:
        ipv4_address: 172.22.0.11
    restart: unless-stopped
    ports:
      - "8989:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      PDNS_ADMIN_SQLA_DB_PASSWORD: "admin-secret-pw"
      PDNS_VERSION: "4.8"
      PDNS_API_KEY: "secret"
    depends_on:
      - pdns-admin-db

  pdns-admin-db:
    image: mariadb:latest
    container_name: pdns-admin-db
    hostname: pdns-admin-db
    networks:
      pdns-net:
        ipv4_address: 172.22.0.10
        aliases:
          - mysql
    restart: unless-stopped
    ports:
      - "5330:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin-secret-pw"
      MYSQL_DATABASE: "pdnsadmin"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin-secret-pw"

networks:
  pdns-net:
    name: pdns-net
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
